# Generated by Django 5.2 on 2025-05-01 04:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.UUIDField()),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phone_num', models.CharField(max_length=20)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('doctor_id', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phone_num', models.CharField(max_length=20)),
                ('dob', models.DateField()),
            ],
        ),
    ]
